name: package_firebase
description: "A new Flutter package project."
version: 0.0.1
#homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_crashlytics: ^3.4.8
  flutter_local_notifications: ^16.2.0
  firebase_remote_config: ^4.3.8
  firebase_storage: ^11.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
